### ISSUE TITLE
import boundary_max_pooling_cuda failed

### ISSUE THREAD

**Issue by twilightmiao** [TencentYoutuResearch/ActionDetection-AFSD#59]
(hurry) root@msl2:/opt/data/private/msl/myAFSD# python3 setup.py develop
running develop
/root/miniconda3/envs/hurry/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/root/miniconda3/envs/hurry/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing AFSD.egg-info/PKG-INFO
writing dependency_links to AFSD.egg-info/dependency_links.txt
writing top-level names to AFSD.egg-info/top_level.txt
reading manifest file 'AFSD.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'AFSD.egg-info/SOURCES.txt'
running build_ext
Creating /root/miniconda3/envs/hurry/lib/python3.7/site-packages/AFSD.egg-link (link to .)
AFSD 1.0 is already the active version in easy-install.pth

Installed /opt/data/private/msl/myAFSD
Processing dependencies for AFSD==1.0
Finished processing dependencies for AFSD==1.0
(hurry) root@msl2:/opt/data/private/msl/myAFSD# python3 AFSD/thumos14/test.py configs/thumos14.yaml --checkpoint_path=models/thumos14/checkpoint-15.ckpt --output_json=thumos14_rgb.json
Traceback (most recent call last):
  File "AFSD/thumos14/test.py", line 9, in <module>
    from AFSD.thumos14.BDNet import BDNet
  File "/opt/data/private/msl/myAFSD/AFSD/thumos14/BDNet.py", line 10, in <module>
    from AFSD.prop_pooling.boundary_pooling_op import BoundaryMaxPooling
  File "/opt/data/private/msl/myAFSD/AFSD/prop_pooling/boundary_pooling_op.py", line 4, in <module>
    import boundary_max_pooling_cuda
ImportError: /opt/data/private/msl/myAFSD/boundary_max_pooling_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by twilightmiao** [comment]
我的cuda版本：10.1
pytorch版本：1.4.0
torch version：0.5.0
这似乎是编译的问题？请问该如何解决呢？
